### ISSUE TITLE
Updating error to include template name instead of path 

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei#148]
Used cmd:- 

```
echo http://xxxx.burpcollaborator.net | nuclei -t /root/nuclei-templates/
```

```diff
[INF] [cms-detect] Loaded template CMS Detect (@NkxxkN https://twitter.com/NkkxN) [informative]
[INF] [Gitlab-Detect] Loaded template Detect Gitlab (@ehsahil) [informative]
[INF] [reverse-proxy-detect] Loaded template Reverse Proxy Detect (@NkxxkN https://twitter.com/NkkxN) [informative]
[INF] [graphql] Loaded template GraphQL API (@NkxxkN) [informative]
[INF] [citrix-vpn-detect] Loaded template Citrix VPN Detection (@bauthard) [informative]
+ [ERR] Could not parse file '/root/nuclei-templates/': No requests defined
[INF] [jira-unauthenticated-dashboards] Loaded template Jira Unauthenticated Dashboards (@TechbrunchFR) [Info]
[INF] [jira-unauthenticated-projects] Loaded template Jira Unauthenticated Projects (@TechbrunchFR) [Info]
[INF] [front-page-misconfig] Loaded template FrontPage configuration information discloure (@JTeles) [info]
```

**Comment by manuelbua** [comment]
This may be simple to fix as it may just need a replacement of `r.options.Templates` with `match` at this line here https://github.com/projectdiscovery/nuclei/blob/master/v2/internal/runner/runner.go#L187.

(can't push as not on my machine)

---

While taking a look at this one i found out that [this condition](https://github.com/projectdiscovery/nuclei/blob/master/v2/internal/runner/runner.go#L466) is always true.

This led me to think about how to handle that cleanly and was thinking about introducing some error types to be able to discern them a bit: for instance, a template without requests and without logic is an ambiguous one as none of the parsers will recognize as a known template, but at this time you can't really know that.

I can see [Go 1.13](https://blog.golang.org/go1.13-errors) has the new Is/As error handling but i keep seeing [this pattern](https://stackoverflow.com/a/39120804/50770) instead, what do you think?

**Comment by Ice3man543** [comment]
@manuelbua good catch, that error handling bit definitely needs to be reworked upon. I was thinking of a making the modules a bit more separate and allowing packages itself to parse them eliminating the logic from that part of the code. This should be fixed in the future when we do a refactor of the code, since the current one has became a bit messy.

**Comment by Lulztigre** [comment]
1 year after i still get this error, is there a simple fix i can push from my end?

**Comment by ehsandeep** [comment]
@Lulztigre Can you include nuclei version? and error details with `-v` flag?
